# Modules/utils/cookies_gen.py

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import os
import tempfile

def generate_dynamic_cookie(user_id: int) -> str:
    """
    Generates a YouTube cookie using Selenium (headless for Heroku)
    Returns cookie string.
    """

    options = Options()
    options.add_argument("--headless=new")  # headless mode for Heroku
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--remote-debugging-port=9222")
    options.add_argument(
        "user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) "
        "AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 "
        "Mobile/14E5239e Safari/602.1"
    )

    driver = webdriver.Chrome(options=options)

    # Open YouTube home (or any page) to get cookies
    driver.get("https://www.youtube.com")

    # Fetch cookies
    cookies = driver.get_cookies()
    driver.quit()

    # Convert cookies to Netscape format string in memory
    cookie_lines = ["# Netscape HTTP Cookie File", "# Generated by @TNCnetwork", "# Thanks for using"]
    for cookie in cookies:
        expiry = cookie.get('expiry') or cookie.get('expires') or 0
        cookie_lines.append(
            f"{cookie['domain']}\tTRUE\t{cookie['path']}\t"
            f"{'TRUE' if cookie.get('secure') else 'FALSE'}\t"
            f"{int(expiry)}\t{cookie['name']}\t{cookie['value']}"
        )

    cookie_text = "\n".join(cookie_lines)
    return cookie_text
